- name: import gpg key
  command: rpm --import https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg

- name: create repository
  template:
    src: vscodium.repo
    dest: /etc/yum.repos.d/vscodium.repo

- name: install vscode
  dnf:
    name: codium
    state: installed
