- name: upgrade all packages
  dnf:
    name: "*"
    state: latest

- name: install common packages
  dnf:
    name: "{{ item }}"
  loop:
  - git
  - htop
  - golang
  - terminator
  - dconf-editor
  - gnome-tweak-tool
