- include_vars: all.yml

- name: upgrade all packages
  dnf:
    name: "*"
    state: latest

- name: install common packages
  dnf:
    name: "{{ item }}"
  loop:
  - git
  - htop
  - golang
  - terminator
  - dconf-editor
  - kernel-devel
  - gnome-tweak-tool

- name: install virtualbox
  dnf:
    state: present
    name: "{{ virtualbox_rpm_url }}"