- name: install dnf-plugins-core
  dnf:
    state: latest
    name: dnf-plugins-core

- name: enable old cgroups
  command: grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"

- name: allow docker in firewall
  command: |
    firewall-cmd --permanent --zone=trusted --add-interface=docker0

- name: allow docker in firewall
  command: |
    firewall-cmd --permanent --zone=FedoraWorkstation --add-masquerade
  
- name: install moby
  dnf:
    state: present
    pkg:
    - moby-engine
    - docker-compose

- name: enable docker service
  command: systemctl enable docker

- name: dont require sudo to run docker
  command: |
    setfacl -m user:{{ansible_user}}:rw /var/run/docker.sock
