- name: install dnf-plugins-core
  dnf:
    state: latest
    name: dnf-plugins-core

- name: remove previous docker instalation
  dnf:
    state: absent
    name: docker-*

- name: disable all docker instalation
  command: dnf config-manager --disable docker-*

- name: enable old cgroups
  command: grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"

- name: allow docker in firewall
  command: |
    firewall-cmd --permanent --zone=trusted --add-interface=docker0
    firewall-cmd --permanent --zone=FedoraWorkstation --add-masquerade
  
- name: install moby
  dnf:
    state: present
    pkg:
    - moby-engine
    - docker-compose

- name: configure service
  command: |
    systemctl enable docker
    systemctl reboot

- name: dont require sudo to run docker
  command: |
    setfacl –modify user:$USER:rw /var/run/docker.sock
