- name: download flat remix icons
  command: git clone https://github.com/daniruiz/flat-remix /tmp/flat-remix

- name: move files to theme folder
  command: bash -c 'cp -r /tmp/flat-remix/Flat-Remix-* /usr/share/icons'

- name: remove git repository
  file:
    state: absent
    path: /tmp/flat-remix

- name: create configuration file
  template:
    src: 10-appearance.conf
    dest: /etc/dconf/db/distro.d/10-appearance.conf

- name: update configurations
  command: dconf update
